# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
# arch: ppc64le
# ... but on the ppc64le, testing in PHP5.4 and PHP5.5 is not possible
arch: amd64

dist: precise

language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - composer update --dev

script:
  - cd test && ../vendor/bin/run_unit_tests
